#!/bin/sh -e
MACOS_VIRT_DIRECTORY=/var/lib/macos-virt
CONTROL_DIRECTORY=$MACOS_VIRT_DIRECTORY/control

mount_control_dir() {
  mkdir -p $CONTROL_DIRECTORY
  mount -t virtiofs control $CONTROL_DIRECTORY
}

mount_control_dir

sh -e $CONTROL_DIRECTORY/service.sh