#!/bin/sh -e

CONTROL_DIRECTORY=/var/lib/macos-virt/control
mount_control_dir() {
  if [ ! -d $CONTROL_DIRECTORY ]
  then
    mkdir -p $CONTROL_DIRECTORY
    mount -t virtiofs control $CONTROL_DIRECTORY
  fi

}

sync_time_wrapper(){
  echo "Setting time"
  rdate -s utcnist.colorado.edu
}

detect_ip() {
  IP_ADDRESS=""
  touch $CONTROL_DIRECTORY/ip_not_detected
  while [ "$IP_ADDRESS" = "" ] ; do
    IP_ADDRESS=$(ip addr | grep "inet " | grep 192.168 | cut -d " " -f6 | cut -d "/" -f1)
    sleep 1;
  done
  echo "$IP_ADDRESS" >> "$CONTROL_DIRECTORY"/ip
  rm $CONTROL_DIRECTORY/ip_not_detected
}


inject_ssh_key(){
  mkdir -p ~macos-virt/.ssh/
  cat "$CONTROL_DIRECTORY"/ssh_key >> ~macos-virt/.ssh/authorized_keys
}

provision_machine(){
  if [ -f "$CONTROL_DIRECTORY"/provision_script ] ; then
    sh -e "$CONTROL_DIRECTORY"/provision_script > "$CONTROL_DIRECTORY"/provision_script_output
    echo $? > "$CONTROL_DIRECTORY"/provision_script_return_code
  fi
}

run_startup_script(){
  if [ -f "$CONTROL_DIRECTORY"/startup_script ] ; then
    sh -e "$CONTROL_DIRECTORY"/startup_script > "$CONTROL_DIRECTORY"/startup_script_output
    echo $? > "$CONTROL_DIRECTORY"/startup_script_return_code
  fi
}

main_loop(){
  while true ; do

    if [ -f "$CONTROL_DIRECTORY"/time_sync ] ; then
      echo "Setting time"
      sync_time_wrapper
      rm "$CONTROL_DIRECTORY"/time_sync
    fi
    if [ -f "$CONTROL_DIRECTORY"/poweroff ] ; then
      echo "Powering off"
      rm "$CONTROL_DIRECTORY"/poweroff
      poweroff
      exit
    fi
    echo "MemoryUsage:" $(free | grep Mem | awk '{print $3/$2 * 100.0}') > "$CONTROL_DIRECTORY"/heartbeat_tmp
    echo "CPUUsage:" $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage }') >> "$CONTROL_DIRECTORY"/heartbeat_tmp
    echo "RootFsUsage:" $(df -h / | tail -1 | awk '{ print $5 }' | tr -d "%" ) >> "$CONTROL_DIRECTORY"/heartbeat_tmp
    mv "$CONTROL_DIRECTORY"/heartbeat_tmp "$CONTROL_DIRECTORY"/heartbeat
    sleep 1
  done
}

resize_root(){
  resize2fs /dev/vda
}
mount_usr_directory(){
  if [ -f "$CONTROL_DIRECTORY"/mnt_usr_directory ] ; then
    usr_directory=$(cat "$CONTROL_DIRECTORY"/mnt_usr_directory)
    if [ ! -d "$usr_directory" ] ; then
      mkdir -p "$usr_directory"
      mount -t virtiofs user-home "$usr_directory"
    fi
  fi
}

mount_control_dir
if [ ! -f "$CONTROL_DIRECTORY"/initialized ] ; then
  inject_ssh_key
  touch "$CONTROL_DIRECTORY"/initialized
fi
resize_root
detect_ip
sync_time_wrapper
mount_usr_directory

if [ ! -f "$CONTROL_DIRECTORY"/initialized ] ; then
  provision_machine
  touch "$CONTROL_DIRECTORY"/initialized
fi
run_startup_script
main_loop








