name: Build X64
on:
  workflow_dispatch:
jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo bash -e build_all.sh
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: virt
    #    path: vmlinuz.tar.gz
