name: Build ARM64
on:
  release:
    types: [published]
jobs:
  build-base:
    runs-on: [self-hosted, Linux, ARM64]
    env: # Or as an environment variable
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - run: sudo bash -e build_all.sh ${{ github.event.release.tag_name }}
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: virt
    #    path: vmlinuz.tar.gz
