name: Build X64
on:
  release:
    types: [published]
env:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build-base:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - uses: actions/checkout@v2
    - run: sudo -E bash -e build_all.sh ${{ github.event.release.tag_name }}
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: virt
    #    path: vmlinuz.tar.gz
